### ISSUE TITLE
Readfile

### ISSUE THREAD

**Issue by 0xboy** [hacksparrow/package-updater#2]
Hello, I'm using this package to update json file but also I'm getting this error on a cron job.
`SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/<path>/node_modules/jsonfile-updater/index.js:100:24
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)`

**Comment by hacksparrow** [comment]
@Ahmetcanb please share the JSON string that's being parsed. It could be that the JSON string is invalid.
